#!/usr/bin/env bash
# Cold-adopt as a Rust-only consumer using shipped templates.
# Skips if cargo-about is missing.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KIT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
GENERATOR="$KIT_DIR/generate-acknowledgements.sh"
EXPANDER="$KIT_DIR/expand-licences.sh"

if ! command -v cargo >/dev/null 2>&1 || ! command -v cargo-about >/dev/null 2>&1; then
  echo "skip: cargo or cargo-about not installed; CI installs cargo-about" >&2
  exit 0
fi

fixture_root="$(mktemp -d)"
trap 'rm -rf "$fixture_root"' EXIT
project="$fixture_root/project"
mkdir -p "$project/src"
cat >"$project/Cargo.toml" <<'EOF'
[workspace]

[package]
name = "cold-adopt"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false
EOF
echo 'fn main() {}' >"$project/src/main.rs"
cat >"$project/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "cold-adopt"
version = "0.1.0"
EOF

cp "$KIT_DIR/ACKNOWLEDGEMENTS.md.template" "$project/ACKNOWLEDGEMENTS.md"
cp "$KIT_DIR/licences.toml.template" "$project/licences.toml"
cp "$KIT_DIR/about.toml.template" "$project/about.toml"
cp "$KIT_DIR/about.hbs.template" "$project/about.hbs"
cat >"$project/attribution.toml" <<'EOF'
[project]
target_path   = "ACKNOWLEDGEMENTS.md"
fixit_command = "generate-acknowledgements.sh"

[[blocks]]
name          = "rust"
ecosystem     = "rust"
manifest_path = "Cargo.toml"
template_path = "about.hbs"
config_path   = "about.toml"
EOF
sed \
  -e 's|{{PROJECT_NAME}}|Fixture|g' \
  -e 's|{{PROJECT_BINARY}}|fixture|g' \
  -e 's|{{GENERATOR_TOOL}}|cargo-about|g' \
  -e 's|{{GENERATOR_TOOL_URL}}|https://github.com/EmbarkStudios/cargo-about|g' \
  -e 's|{{LOCKFILE_NAME}}|Cargo.lock|g' \
  -e 's|{{GENERATOR_SCRIPT_PATH}}|generate-acknowledgements.sh|g' \
  -e 's|{{BLOCK_NAME}}|rust|g' \
  "$project/ACKNOWLEDGEMENTS.md" >"$project/ACKNOWLEDGEMENTS.md.tmp"
mv "$project/ACKNOWLEDGEMENTS.md.tmp" "$project/ACKNOWLEDGEMENTS.md"

if ! (cd "$project" && "$EXPANDER"); then
  echo "fail: expander refused Rust-only bootstrap" >&2
  exit 1
fi
if ! (cd "$project" && "$GENERATOR" --config attribution.toml); then
  echo "fail: documented generator command failed on a Rust-only cold adopt" >&2
  exit 1
fi
if ! (cd "$project" && "$GENERATOR" --config attribution.toml --check); then
  echo "fail: --check drifted after Rust cold adopt" >&2
  exit 1
fi
echo "ok: documented Rust-only cold adopt generates and --check is green"
